### ISSUE TITLE
Biopython package missing in environment.yml

### ISSUE THREAD

**Issue by jesperswillem** [GIST-CSBL/HoTS#1]
Dear authors,

Thanks for your excellent work, I noticed whilst running the jupyter notebook that the biopython package was not installed with the environment.yml file. I manually installed it (conda install -c conda-forge biopython), after which everyting was fine. Perhaps the package can be added to the environment.yml file, or added as a prerequisite in the README?

Kind regards,

Willem Jespers

**Comment by dlsrnsi** [comment]
Dear Jesper Willem,

Thank you for informing us that our environment file does not contain the Biopython package.

As your kind recommendation, we add `biopython=1.79=py36h8f6f2f9_0` and corresponding pre-requisite packages to our `envrironment.yml` file.

Sincerely,

Ingoo Lee

**Comment by dlsrnsi** [comment]
Thank you for your suggestion, again.

I will close this issue.

**Comment by alex-golts** [comment]
I noticed that biopython still seems to be missing from the environment.yml file in the current master branch
