### ISSUE TITLE
Generating BR Data

### ISSUE THREAD

**Issue by busraoguzoglu** [GIST-CSBL/HoTS#3]
Hello,

I want to generate BR training data using Parsing_scPDB_for_HoTS file, however I do not have the scPDB data.  
When I searched, I have found that it can be reached via this link: http://bioinfo-pharma.u-strasbg.fr/scPDB/ but I guess the page is down or there is a problem on the site. 
Did you get the scPDB data from this link? If I understand correctly Training_HoTS and and Validation_HoTS.tsv files are samples, and full training files can be generated using Parsing_scPDB_for_HoTS.ipynb, but I need to have scPDB data available on my computer is this correct? Do you know if there is any other way to reach scPDB data? 

Thanks a lot for your help.

**Comment by busraoguzoglu** [comment]
Turns out there was a problem on the website, it is working today.

**Comment by busraoguzoglu** [comment]
Dear authors,

When I downloaded the latest version of scPDB from the website, I have found that the .pdb file format has been changed with .mol2. Because of this, Parsing_scPDB_for_HoTS.ipynb file is not working. Do you know if there is any way to make a conversion between these two file formats using Python?

Thanks a lot

**Comment by dlsrnsi** [comment]
Dear @busraoguzoglu 

You can use Babel to convert mol2 to pdb.

https://openbabel.org/docs/dev/Command-line_tools/babel.html

Sorry for the late answer.

Sincerely,

Ingoo Lee
